### ISSUE TITLE
openRtpServer失败,但是msg信息看不懂

### ISSUE THREAD

**Issue by LECYWZA** [ZLMediaKit/ZLMediaKit#2081] opened 2022-11-10 08:11 UTC
有时候创建国标收流器失败,但是返回的信息看不懂, 以前版本的ZLM返回还是中文或者英文的, 
现在的我unicode转文字也是乱码.....

POST /index/api/openRtpServer

# header:

Accept : text/html,application/json,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8

Accept-Encoding : gzip, deflate

Accept-Language : zh-CN,zh;q=0.8

Cache-Control : no-cache

Connection : keep-alive

Content-Length : 130

Content-Type : application/x-www-form-urlencoded;charset=UTF-8

Host : 192.168.0.1:6080

Pragma : no-cache

User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 Hutool

# content:

port=0&stream_id=34020000001320000001_34020000001310000001&ssrc=199907974&enable_tcp=1&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc

# response:

{
	"code" : -300,
	"msg" : "\u0603stream_id\u0491\u0526\u051a"
}

**Comment by liuzh0324y** [comment] 2022-11-24 03:45
windows配置文件里有个http字符编码，改动一下试试

**Comment by liuzh0324y** [comment] 2022-11-24 09:28
Duplicate of #

> 有时候创建国标收流器失败,但是返回的信息看不懂, 以前版本的ZLM返回还是中文或者英文的, 现在的我unicode转文字也是乱码.....
> 
> POST /index/api/openRtpServer
> 
> # header:
> Accept : text/html,application/json,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
> 
> Accept-Encoding : gzip, deflate
> 
> Accept-Language : zh-CN,zh;q=0.8
> 
> Cache-Control : no-cache
> 
> Connection : keep-alive
> 
> Content-Length : 130
> 
> Content-Type : application/x-www-form-urlencoded;charset=UTF-8
> 
> Host : 192.168.0.1:6080
> 
> Pragma : no-cache
> 
> User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 Hutool
> 
> # content:
> port=0&stream_id=34020000001320000001_34020000001310000001&ssrc=199907974&enable_tcp=1&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
> 
> # response:
> { "code" : -300, "msg" : "\u0603stream_id\u0491\u0526\u051a" }

参数port=0的目的是啥？把port=0去掉就好了

**Comment by xia-chu** [comment] 2022-11-24 09:33
json是把中文序列化了 你要反序列化才行啊

**Closed by xia-chu** 2022-11-24 09:33 UTC
Labels: 技术咨询
