### ISSUE TITLE
Some rtsp stream source error when play with ffplay

### ISSUE THREAD

**Issue by thaibienbac** [zlmediakit/ZLMediaKit#66] opened 2019-08-15 02:17 UTC
Hi,

I am using your "test_server" to connect to rtsp stream source (this source is available, you can using it to test): rtsp://admin:admin@118.70.125.33:21154/CH002.sdp

ffplay can not play rtsp stream: rtsp://127.0.0.1/live/0 while VLC play well.
Some other rtsp stream sources dont have this problem.
can you help me to fixed it?

![rtsp stream](https://user-images.githubusercontent.com/13082850/63068355-13f14500-bf3d-11e9-8212-a21a11a935eb.jpg)

**Comment by xiongziliang** [comment] 2019-08-15 05:46
I can not open the rtsp(`rtsp://admin:admin@118.70.125.33:21154/CH002.sdp`) url you provided.
You can open the url `rtsp://127.0.0.1/live/0` with ffplay , and capture the `rtsp or rtp` pacekt by `wireshark` like this:
![image](https://user-images.githubusercontent.com/11495632/63075131-1c5c7680-bf63-11e9-9e68-ef7e3014a470.png)

**Comment by thaibienbac** [comment] 2019-08-15 06:25
Hi,

this rtsp source still available, you can try with VLC.
atteched file is wireshark capture.

[Wireshark_capture.zip](https://github.com/zlmediakit/ZLMediaKit/files/3504487/Wireshark_capture.zip)

![rtsp_source](https://user-images.githubusercontent.com/13082850/63076644-1c0eac00-bf60-11e9-9091-758557b329be.jpg)

**Comment by xiongziliang** [comment] 2019-08-15 07:33
I mean you open the url(`rtsp://127.0.0.1/live/0`) proxyed by ZLMediaKit using ffplay.

**Comment by xiongziliang** [comment] 2019-08-15 07:33
> I mean you open the url(`rtsp://127.0.0.1/live/0`) proxyed by ZLMediaKit using ffplay.

So i can find out that why ffplay can not played successed!

**Comment by thaibienbac** [comment] 2019-08-15 08:13
Hi,

this is wireshark captured when open url (rtsp://127.0.0.1/live/0) proxyed by ZLMediaKit using ffplay.

[ffplay.zip](https://github.com/zlmediakit/ZLMediaKit/files/3504769/ffplay.zip)

**Comment by xiongziliang** [comment] 2019-08-15 10:15
I know why failed now.
I will fixed this later soon.

**Comment by xiongziliang** [comment] 2019-08-15 11:16
This bug is fixed just now ,please update the newest code.

**Comment by thaibienbac** [comment] 2019-08-15 11:58
Hi,

It's work fine. 
I am trying with other rtsp stream, this is 4K (3840x2160) resolution
rtsp://Admin:1234@118.70.125.33:22354/h264

seem some frames droped:
test_server.exe(11052) d:\github\zlmediakit\src\extension\h264rtp.cpp 162
2019-08-15 18:11:12.770 W | mediakit::H264RtpDecoder::decodeRtp rtp sequence不连续: 20457 != 5 + 1,该帧被废弃

**Comment by xiongziliang** [comment] 2019-08-16 04:03
Can you lower the resolution of this camera?
I can't connect your camera often.

After setting the camera ,please reboot it.

**Comment by thaibienbac** [comment] 2019-08-16 04:53
Hi,

Dropped frame only occurs with stream at high resolution.
I am setting bitrate = 1536 Kbps, frame rate = 5 fps.
Please test again.

**Comment by xiongziliang** [comment] 2019-08-19 04:04
I'm sorry, I've tried many ways, and I can't decode your RTSP stream at the moment.
Your RTSP flow seems to be a bit problematic. His RTP fragmentation is fu-a, but there is no start bit. I tried to circumvent the restriction that there must be a start bit, but the resulting H264 frame still can not be decoded. Sorry, I'm already energetic. I'll let you know later when I have news.

**Comment by xiongziliang** [comment] 2019-08-19 15:11
This is a bug caused by data overflow, i fixed by this:
![image](https://user-images.githubusercontent.com/11495632/63276770-a0ea2480-c2d6-11e9-9051-278a2416902a.png)

**Closed** 2019-08-19 15:11 UTC
